### ISSUE TITLE
Minor error when tube line is closed for the night

### ISSUE THREAD

**Issue by cyberdelica** [smallwat3r/tubestatus#9]
When the tube line is closed for the night, the API returns the integer `20` for the `.statusSeverity`.

With the current script, that means a yellow traffic light indicator - obviously not right - when it should be red.

It's a minor fix that seems too trivial to make a pull request for.

**Comment by smallwat3r** [comment]
Thanks for spotting this @cyberdelica 
I edited the code to take this severity code into account.
